[package]
name = "servicepoint-life"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
rand = "0.9.0-alpha.1"
env_logger = "0.11.3"
servicepoint2 = "0.4.1"
crossterm = "0.27.0"
log = "0.4.21"
