[package]
name = "servicepoint-life"
version = "0.2.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Small terminal app that generates conways game of life rules and simulates them on the servicepoint display."
repository = "https://git.berlin.ccc.de/vinzenz/servicepoint-life"
readme = "README.md"
keywords = ["cccb", "cccb-servicepoint", "conway", "game-of-life", "simulation"]
rust-version = "1.70.0"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rand = "0.8"
crossterm = "0.29"

[dependencies.servicepoint]
package = "servicepoint"
version = "0.14.0"
features = ["rand"]
git = "https://git.berlin.ccc.de/servicepoint/servicepoint/"
branch = "next"

[lints.clippy]
incompatible_msrv = "forbid"

[profile.release]
lto = true          # Enable link-time optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations

[profile.size-optimized]
inherits = "release"
opt-level = 'z'     # Optimize for size
panic = 'abort'     # Abort on panic
strip = true        # Strip symbols from binary
